### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by oponomarov-tu** [idoavrah/terraform-tui#10]
Hey! First and foremost -- thanks for the amazing tool! 

It looks like currently the installation with `pip` is broken:

```text
Traceback (most recent call last):
  File "/Users/esolidarity/.virtualenvs/default/bin/tftui", line 5, in <module>
    from tftui.__main__ import main
  File "/Users/esolidarity/.virtualenvs/default/lib/python3.10/site-packages/tftui/__main__.py", line 3, in <module>
    from textual.widgets import Header, Footer, Tree, TextLog, LoadingIndicator, ContentSwitcher, Static, Button
  File "/Users/esolidarity/.virtualenvs/default/lib/python3.10/site-packages/textual/widgets/__init__.py", line 94, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'TextLog'
```

Quick googling revealed [this](https://github.com/Textualize/textual/blob/main/FAQ.md#no-widget-called-textlog), so installing `textual==0.31.0` fixed the issue.

**Comment by idoavrah** [comment]
This was caused by pipx / workstation installing an upgraded version of textual (0.32.0 and later). Textual moved away from using the TextLog class and changing it to a RichLog class (without backward compatibility).
I upgraded to textual 0.32 and fixed the breaking change. 

Please upgrade tftui and thanks for the catch :)
